config/routes.rb
HospitalLink::Application.routes.draw do
  

  root  to: 'static_pages#home', via: 'get'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :submissions
  resources :courses
  resources :attachments
  resources :credits
  post '/submit/:course', to: 'submissions#submit', as: :submit
  post '/upload', to: 'submissions#upload' , as: :upload
  get  '/download', to: 'submissions#download' , as: :download
  get '/instructors/request/accept/:id', to: 'users#accept' , as: :accept_request
  get '/instructors/requests', to: 'users#requests', as: :request
  get 'submissions/grades/pending' ,to: 'submissions#assignments_to_grade', as: :assign_to_grade
  get '/student/grades/:id', to: 'submissions#my_grades', as: :my_grades
  get '/students/submissions/:id', to: 'submissions#student', as: :student_submissions
  get '/students/points/:id', to: 'submissions#student_rewards', as: :student_rewards
  get 'tags/:tag', to: 'courses#index', as: :tag
  get 'students/rewards/:id' , to: 'submissions#tutorials_completed', as: :rewards
  match '/instructors', to: 'users#instructors', via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signup/students', to: 'users#new' , via: 'get'
  match '/help', to:  'static_pages#help' , via: 'get'
  match '/about', to:   'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact' , via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/signup/instructors', to: 'users#new_instructors', via: 'get'
  match '/create/instructors', to: 'users#create_instructors', via: 'post'
  match '/students', to: 'users#students', via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :submissions,inverse_of: :user, :dependent => :destroy
  has_one  :credit
  ActiveModel::ForbiddenAttributesProtection
  before_create :create_remember_token
  before_save { self.email = email.downcase }
  attr_accessible :email,:credit, :first_name, :last_name, :password, :password_confirmation, :remember_token, :instruc

  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates :email, presence: true,format: { with: VALID_EMAIL_REGEX },uniqueness:{ case_sensitive: false }

  has_secure_password

  def self.instructors_requests
    User.where(:status => "pending")
  end
  def self.instructors
    User.where('instruc' => true)
  end
  def self.students
    User.where('instruc' => false, 'admin' => false, 'status' => "approved")
  end
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user , only: [:index,:edit,:update]
  before_filter :correct_user, only: [:edit, :update]
  before_filter :admin_user, only: [:destroy]
  def show
    @user = User.find(params[:id]) # look up user by unique ID
  end

  def index
    @users = User.all
  end
  def students
    @students = User.students.paginate(:page => params[:page],per_page: 5)
  end
  def instructors
    @instructors = User.instructors.paginate(:page => params[:page],per_page: 5)
  end

  def new
    # default: render 'new' template
  end
  def requests
    @req = User.instructors_requests.paginate(:page => params[:page],per_page: 5)
  end
  def accept
    @user = User.find(params[:id])
    @user.status = "approved"
    @user.instruc = true
    if @user.save
      UserMailer.welcome_instructor(@user).deliver
      flash.now[:success] = "Thanks for approving Mr #{@user.first_name} #{@user.last_name} as an instructor!"

    else
      flash.now[:error] = "Sorry #{@user.first_name} #{@user.instruc} #{@user.status} #{@user.password}"
    end

  end
  def create_instructors
    @user = User.new(params[:user])
    if @user.password.blank? or @user.password.length <6
      flash[:error] =". Password should be at least six characters long"
      #redirect_to signup_instructor_path
    elsif @user.password_confirmation.blank? or @user.password_confirmation.length <6
      flash[:error] = ". Password confirmation should be at least six characters long"
      #redirect_to signup_instructor_path
    else
      @user.status = "pending"
      if @user.save
        UserMailer.verify_instructor(@user).deliver
        flash.now[:success]= "Your request was sent to the administrator"
        redirect_to root_path
      else
        flash.now[:error] = "You did not enter all the fields correctly"
        #redirect_to signup_instructor_path
      end
    end
  end
  def create
    @user = User.new(params[:user])
    if @user.password.blank? or @user.password.length <6
      flash[:error] =". Password should be at least six characters long"
      if @user.password_confirmation.blank?
	      flash[:error] = ". Please enter the password confirmation"
      end
      render 'new'
    #elsif @user.password_confirmation.blank? or @user.password_confirmation.length <6
      #flash[:error] = ". Please enter the password confirmation"
      #render 'new'
    else
      @user.instruc = false
      @user.status = "approved"
      if @user.save
        Credit.create!(:user_id => @user.id,:credit =>0)
        sign_in @user
        flash[:success] = "Welcome to ImagineWare Online Course Platform."
        redirect_to user_path(@user)
      else
        flash.now[:error] = "You did not enter all the fields correctly"
        render 'new'
      end
    end
    #redirect_to users_path
  end
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash.now[:notice] = "User '#{@user.first_name}' deleted."
    redirect_to instructors_path
  end
  def edit
    @user = User.find params[:id]
  end

  def update
    
    if @user.update_attributes(user_params)
      flash[:success] ="Profile updated"
      redirect_to user_path(@user)
    else
      flash[:error] = "Invalid update informations"
      render 'edit'
    end
  end
  private 
    def user_params
      params.require(:user).permit(:first_name,:last_name, :email, :password,:password_confirmation)
    end
    def signed_in_user
      redirect_to signin_url, notice: "Please sign in!" unless signed_in?
    end
    def correct_user
      @user = User.find(params[:id])
      redirect_to (root_url) unless current_user?(@user)
    end
    def admin_user
      redirect_to (root_path) unless current_user.admin?
    end

end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.first_name, class: "gravatar")
  end
end

app/views/users/_user.html.haml
%li
  //= gravatar_for user, size: 52
  = link_to user.first_name + '  ' + user.lastname, user
  - if current_user.admin? && !current_user?(user)
    | #{link_to "delete", user, method: :delete, data: { confirm: "You sure?" }}

app/views/users/credit_account.html.haml
%h2 Credit student's account
.row
  .span6.offset3
    = simple_form_for :credit, :url => {:action => :credit_account , :method => :put} do |f|
      %p= f.label :credit_points
      %p= f.text_field :credit_points
      %p= f.submit "Add credit", class: "btn btn-large btn-primary"
=debug(@param)
=debug(@cre)

app/views/users/edit.html.haml
- provide(:title, "Edit user")
%h1 Update your profile
.row
  .span6.offset3
    = form_for(@user) do |f|
      = f.label :first_name
      = f.text_field :first_name
      = f.label :last_name
      = f.text_field :last_name
      = f.label :email
      = f.text_field :email
      = f.label :password
      = f.password_field :password
      = f.label :password_confirmation, "Confirm Password"
      = f.password_field :password_confirmation
      = f.submit "Save changes", class: "btn btn-large btn-primary"

app/views/users/index.html.haml
- provide(:title, 'All users')
%h2 All users
%table{:class => "table table-striped table-bordered table-condensed"}
 %thead
  %tr
   %th Avatar
   %th User id
   %th First Name
   %th Last Name
   %th Email
  %tbody
   - @users.each do |user|
    %tr
     %td= gravatar_for @user, size: 52
     %td= link_to "#{user.id}", user_path(user)
     %td= "#{user.first_name}"
     %td= "#{user.last_name}"
     %td= "#{user.email}"

app/views/users/instructors.html.haml
- provide(:title, 'All instructors')
%h2 All instructorss
%ul.instructors
  - @instructors.each do |instructor|
    %li
      //= gravatar_for student
      #{instructor.first_name} #{instructor.last_name}
      | #{link_to "delete", instructor, method: :delete ,data: {confirm: "Are you sure?"}}
= will_paginate @instructors

app/views/users/new.html.haml
- provide(:title, 'Sign up')
%h1 Sign up
%center
  .row
    .span6.offset3
      = simple_form_for :user , :url => {:action => :create } do |f|
        %p= f.label :First_Name
        %p= f.text_field :first_name
        %p= f.label :Last_Name
        %p= f.text_field :last_name
        %p= f.label :email
        %p= f.text_field :email
        %p= f.label :password
        %p= f.password_field :password
        %p= f.label :password_confirmation, "Confirmation"
        %p= f.password_field :password_confirmation
        %p= f.submit "Create my account", class: "btn btn-large btn-primary"

app/views/users/new_instructors.html.haml
- provide(:title, 'Sign up')
%h1  Sign up
%center
  .row
    .span6.offset3
      = simple_form_for :user , :url => {:action => :create_instructors } do |f|
        %p= f.label :First_Name
        %p= f.text_field :first_name
        %p= f.label :Last_Name
        %p= f.text_field :last_name
        %p= f.label :email
        %p= f.text_field :email
        %p= f.label :password
        %p= f.password_field :password
        %p= f.label :password_confirmation, "Confirmation"
        %p= f.password_field :password_confirmation
        %p= f.submit "Create my account", class: "btn btn-large btn-primary"

app/views/users/render.html.haml
= render "shared/error_messages", :target => @user

app/views/users/requests.html.haml
- provide(:title, 'All instructors')
%h2 Instructors requests
%ul.requests
  - @req.each do |instructor|
    %li
      //= gravatar_for student
      #{instructor.first_name} #{instructor.last_name}
      | #{link_to "accept", accept_request_path(instructor)}
      | #{link_to "deny", instructor, method: :delete , data: {confirm: "Are you sure ?"}} 
= will_paginate @req

app/views/users/show.html.haml
- provide(:title, @user.first_name + @user.last_name)
.row
  %aside.span4
    %h1
      =gravatar_for @user
      =[@user.first_name, @user.last_name].reject(&:empty?).join(' ')
      -if current_user.instruc == false and current_user.admin == false
        %h6
        .content
          %p Total reward:#{Submission.where(:user_id => session[:current_user]).sum(:points)}
          %p
            Current credit:#{Credit.find_by_user_id(session[:current_user]).credit}

app/views/users/students.html.haml
- provide(:title, 'All students')
%h2 All students
%ul.students
  - @students.each do |student|
    %li
      //= gravatar_for student
      = link_to student.first_name + ' ' + student.last_name, student_submissions_path(student)
      -if current_user and current_user.admin
        | #{link_to "delete", user_path(student), :method => :delete, data: {confirm: " Are You Sure ?"}}
= will_paginate @students