config/routes.rb
HospitalLink::Application.routes.draw do
  

  root  to: 'static_pages#home', via: 'get'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :submissions
  resources :courses
  resources :attachments
  resources :credits
  post '/submit/:course', to: 'submissions#submit', as: :submit
  post '/upload', to: 'submissions#upload' , as: :upload
  get  '/download', to: 'submissions#download' , as: :download
  get '/instructors/request/accept/:id', to: 'users#accept' , as: :accept_request
  get '/instructors/requests', to: 'users#requests', as: :request
  get 'submissions/grades/pending' ,to: 'submissions#assignments_to_grade', as: :assign_to_grade
  get '/student/grades/:id', to: 'submissions#my_grades', as: :my_grades
  get '/students/submissions/:id', to: 'submissions#student', as: :student_submissions
  get '/students/points/:id', to: 'submissions#student_rewards', as: :student_rewards
  get 'tags/:tag', to: 'courses#index', as: :tag
  get 'students/rewards/:id' , to: 'submissions#tutorials_completed', as: :rewards
  match '/instructors', to: 'users#instructors', via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signup/students', to: 'users#new' , via: 'get'
  match '/help', to:  'static_pages#help' , via: 'get'
  match '/about', to:   'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact' , via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/signup/instructors', to: 'users#new_instructors', via: 'get'
  match '/create/instructors', to: 'users#create_instructors', via: 'post'
  match '/students', to: 'users#students', via: 'get'

end

app/models/submission.rb
class Submission < ActiveRecord::Base
  attr_accessible :grader_id , :grade, :feedback, :user, :course, :attachment
  belongs_to :user, inverse_of: :submissions
  belongs_to :course, inverse_of: :submissions
  has_one    :attachment, :class_name => 'Attachment', :foreign_key => 'attachment_id'
  def self.new_submission
    new { |u| u.feedback = "student's submission", u.grade = "Pending"}
  end
  def self.tutorials_completed(id,arr)
    Submission.where(user_id: id, grade: arr)
  end
  def self.my_grades(id)
    Submission.where(:user_id => id)
  end
  def self.non_graded_assignments
    Submission.where(:grade => 'Pending')
  end
  def self.student_submissions(id)
    Submission.where('user_id' =>id.to_i)
  end

=begin
  def self.save(upload)
    name =  upload['datafile'].original_filename
    directory = "upload/public"
    #directory = Rails.root.join("upload","public","data");
    # create the file path
    #path = File.join(directory, name)
    # write the file
    #File.open(path, "wb") { |f| f.write(upload['datafile'].read) }
    File.open(Rails.root.join('public', 'upload', name), 'w') do |file|
      file.write(upload['datafile'].read)
    end
  end
=end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  def my_grades
    @my_sub = Submission.my_grades(session[:current_user])
  end
  def tutorials_completed
    @completed = Submission.tutorials_completed(session[:current_user],Course.all_grades)
  end


  def assignments_to_grade
    @to_grade = Submission.non_graded_assignments
  end
  def show
    @submission = Submission.find(params[:id])
  end
  def student
    @student_submissions = Submission.student_submissions(params[:id])
    @id = params[:id]
    session[:stu] = @id
  end
  def student_rewards
    @stud_rewa = Submission.tutorials_completed(params[:id],Course.all_grades)

    @student_reward = Submission.where(:user_id => params[:id]).sum(:points)
  end
  def index
    @submissions = Submission.all
  end
  def new
  end
  def upload
    return if params[:attachment].blank?

    @attachment = Attachment.new
    @attachment.uploaded_file = params[:attachment]

    if @attachment.save
      flash[:notice] = "Your file was successfully attached please press on submit assignment..."
      redirect_to  :back
      session[:file_id] = @attachment.id
    else
      flash[:error] = "There was a problem submitting your attachment."
      redirect_to upload_path
    end
  end
  
  def submit
    @submission = Submission.new_submission
    @submission.attachment_id = session[:file_id]
    @submission.user_id = session[:current_user]
    @submission.course_id = session[:course]
    if @submission.save
      flash.now[:success] = "Your submission was successful"
      flash.keep
    end
    redirect_to student_submissions_path(session[:current_user])
  end

  def edit
    @submission = Submission.find params[:id]
    session[:file_id] = @submission.attachment_id
  end
  def download
    @attachment = Attachment.find(session[:file_id])
    send_data @attachment.data, :filename => @attachment.filename, :type => @attachment.content_type 
  end

  def update
    @submission = Submission.find params[:id]
    @submission.grader_id = session[:current_user].to_i
    if params[:submission][:grade] != "F"
      @submission.points = Course.find(@submission.course_id).points
    else
      @submission.points = 0
    end
    @submission.update_attributes!(params[:submission])
    UserMailer.assignment_graded(@submission).deliver
    flash[:success] = "#{User.find(@submission.user_id).first_name}'s submission for #{Course.find(@submission.course_id).title} has been graded"
    redirect_to root_path
  end

end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/assignments_to_grade.html.haml
%h2 Assignments to be graded
%table{:class => "table table-striped table-bordered table-condensed"}
 %thead
  %tr
   %th Student Name
   %th Course
   %th Grade
   %th Date Submitted
   %th Feedback
  %tbody
   - @to_grade.each do |submission|
    %tr
     %td= User.find(submission.user_id).first_name + ' ' + User.find(submission.user_id).last_name
     %td= link_to "#{Course.find(submission.course_id).title}",submission_path(submission)
     %td= submission.grade
     %td= submission.created_at
     %td= submission.feedback

app/views/submissions/edit.html.haml
%h2 Grade Assignment


=form_tag submission_path(@submission), :method => :put do

  %p= link_to 'Download Assignment' ,download_path
  %p=label :submission, :grade, 'Grade'
  %p= select  :submission, :grade, Course.all_grades

  %p=label :submission, :feedback, 'Feedback'
  %p=text_area :submission,'feedback', :rows => 5, :class => "span3", :placeholder => 'Enter text.'
  %p=submit_tag 'Submit grade', class: "btn btn-medium btn-primary"

app/views/submissions/index.html.haml
-#  This file is app/views/submissions/index.html.haml
%h2 All Submissions
%table{:class => "table table-striped table-bordered table-condensed"}
 %thead
  %tr
   %th Course
   %th Grade
   %th Date Submitted
   %th Feedback
  %tbody
   - @submissions.each do |submission|
    %tr
     %td= "#{-Course.find(submission.course_id).title}"
     %td= "#{submission.grade}"
     %td= "#{submission.created_at}"
     %td= link_to "See your feedback for #{-Course.find(submission.course_id).title}", submission_path(submission.id)

app/views/submissions/my_grades.html.haml
-#  This file is app/views/submissions/index.html.haml
%h2 All Submissions
%table{:class => "table table-striped table-bordered table-condensed"}
 %thead
  %tr
   %th Course
   %th Grade
   %th Date Submitted
   %th Feedback
   %th File Uploaded
  %tbody
   - @my_sub.each do |submission|
    %tr
     %td= Course.find(submission.course_id).title
     %td= submission.grade
     %td= submission.created_at
     %td= link_to "See your feedback for #{Course.find(submission.course_id).title}", submission_path(submission.id)
     %td= link_to 'Download Assignment' ,download_path

app/views/submissions/show.html.haml
- 
%h2 #{User.find(@submission.user_id).first_name} #{User.find(@submission.user_id).last_name} assignment for #{Course.find(@submission.course_id).title}
%ul#details
  %li
    Date Submitted:
    = @submission.created_at
  %li
    Grade:
    = @submission.grade
  %li
    Feedback:
    = @submission.feedback
-if current_user.instruc? or current_user.admin?
  =link_to 'grade assignment', edit_submission_path(@submission)

app/views/submissions/student.html.haml
-if current_user.admin? or current_user.instruc?
 %h6
 .content
  %p= link_to "Student's reward : #{Submission.where(:user_id =>@id).sum(:points)}", student_rewards_path(@id)
  %p Student's current credit :#{Credit.find_by_user_id(@id).credit}
-if current_user.admin?
 %h6
 .content
  %p= link_to "Add credit to student", new_credit_path
%h2 All Submissions
%table{:class => "table table-striped table-bordered table-condensed"}
 %thead
  %tr
   %th Course
   %th Grade
   %th Date Submitted
   %th Feedback
   %th File Uploaded
  %tbody
   - @student_submissions.each do |submission|
    %tr
     %td= link_to "#{Course.find(submission.course_id).title}",submission_path(submission)
     %td= submission.grade
     %td= submission.created_at
     %td= submission.feedback
     %td= link_to 'Download Assignment' ,download_path

app/views/submissions/student_rewards.html.haml
%h2 All Tutorials completed
%table{:class => "table table-striped table-bordered table-condensed"}
  %thead
    %tr
      %th Course
      %th Date Completed
      %th Points Awarded
    %tbody
      - @stud_rewa.each do |tutorial|
        %tr
          %td= "#{Course.find(tutorial.course_id).title}"
          %td= tutorial.created_at
          %td= tutorial.points

app/views/submissions/tutorials_completed.html.haml
%h2 All Tutorials completed
%table{:class => "table table-striped table-bordered table-condensed"}
  %thead
    %tr
      %th Course
      %th Date Completed
      %th Points Awarded
    %tbody
      - @completed.each do |tutorial|
        %tr
          %td= "#{Course.find(tutorial.course_id).title}"
          %td= tutorial.created_at
          %td= tutorial.points