config/routes.rb
HospitalLink::Application.routes.draw do
  

  root  to: 'static_pages#home', via: 'get'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :submissions
  resources :courses
  resources :attachments
  resources :credits
  post '/submit/:course', to: 'submissions#submit', as: :submit
  post '/upload', to: 'submissions#upload' , as: :upload
  get  '/download', to: 'submissions#download' , as: :download
  get '/instructors/request/accept/:id', to: 'users#accept' , as: :accept_request
  get '/instructors/requests', to: 'users#requests', as: :request
  get 'submissions/grades/pending' ,to: 'submissions#assignments_to_grade', as: :assign_to_grade
  get '/student/grades/:id', to: 'submissions#my_grades', as: :my_grades
  get '/students/submissions/:id', to: 'submissions#student', as: :student_submissions
  get '/students/points/:id', to: 'submissions#student_rewards', as: :student_rewards
  get 'tags/:tag', to: 'courses#index', as: :tag
  get 'students/rewards/:id' , to: 'submissions#tutorials_completed', as: :rewards
  match '/instructors', to: 'users#instructors', via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signup/students', to: 'users#new' , via: 'get'
  match '/help', to:  'static_pages#help' , via: 'get'
  match '/about', to:   'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact' , via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/signup/instructors', to: 'users#new_instructors', via: 'get'
  match '/create/instructors', to: 'users#create_instructors', via: 'post'
  match '/students', to: 'users#students', via: 'get'

end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < Admin::BaseController
  def index
  end

  def new
  end

  def create
    #@course = Course.create!(params[:Course])
    #flash[:notice] = "#{@course.title} was successfully created."
    #redirect_to courses_path
  end

  def edit
    #@course = Course.find params[:id]
  end

  def update
    #@course = Course.find params[:id]
    #@course.update_attributes!(params[:Course])
    #flash[:notice] = "#{@course.title} was successfully updated."
    #redirect_to course_path(@course)
  end

  def destroy
    #@course = Course.find(params[:id])
    #@course.destroy
    #flash[:notice] = "Course '#{@course.title}' deleted."
    #redirect_to courses_path
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @pasta = params[:tag]
    if params[:tag]
      @courses = Course.tagged_with(params[:tag], :any => true)
    else
      @courses = Course.all
    end
  end

  def show
    @course = Course.find(params[:id])
    session[:course] = @course.id
  end

  def new
  end

  def create
    @course = Course.new(params[:course])
    if @course.save
      flash[:success] = "#{@course.title} was successfully created."
      redirect_to courses_path
    else
      flash[:error] = "Your course was not properly created"
    end

  end
  
  

  #def index
  #  @all_tags = Course.all_tags
  #  @selected_tags = params[:tags] || session[:tags] || {}
  #  
  #  if @selected_tags == {}
  #    @selected_tags = Hash[@all_tags.map {|tag| [tag, tag]}]
  #  end
  #  
  #  if params[:tags] != session[:tags]
  #    session[:tags] = @selected_tags
  #    redirect_to :tags => @selected_tags and return
  #  end
  #  @courses = [Course.create!(:title => "Introduction to HTML5", :tags => "beginner", :content => "This is and HTML5 course. You must build a website from sratch")]
  #  @selected_tags.each_key do |tag|
  #    @courses.concat(Course.find_all_by_tags(tag))
  #  end 
  #end

  def edit
    @course = Course.find params[:id]
  end

  def update
    @course = Course.find params[:id]
    @course.update_attributes!(params[:course])
    flash[:notice] = "#{@course.title} was successfully updated."
    redirect_to course_path(@course)
  end
  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    flash[:notice] = "Course '#{@course.title}' deleted."
    redirect_to courses_path
  end
end

app/views/courses/autocomplete.html.haml
= form_tag do
  = text_field_tag 'title', '', :autocomplete => course_autocomplete_course_path

app/views/courses/edit.html.haml
%h1 Edit course
.row
  .span6.offset3
    = form_tag course_path(@course), :method => :put do
      %p= label :course,:Course_Title
      %p= text_field :course,:title
      %p= label :course,:Points
      %p= text_field :course,:points
      %p= label :course,:Description
      %p= text_area :course,:content, :rows => 5, :class => "span3", :placeholder => "Enter text"
      %p= submit_tag "Create course", class: "btn btn-large btn-primary"

app/views/courses/index.html.haml
-#  This file is app/views/courses/index.html.haml
%h2 All Courses


%center
  %div#tag_cloud
    - tag_cloud Course.tag_counts, %{s m l} do |tag, css_class|
      = link_to tag.name, tag_path(tag.name), class: css_class
  = @pasta
  %table{:class =>"table table-striped table-bordered table-condensed" }

    %thead
      %tr
        %th Logo
        %th Course Title
        -#%th content
        
    %tbody
      - @courses.each do |course|
        -if course.title.downcase.include? "python"
          %tr
            %td= link_to image_tag("python.gif"), "#"
            %td= link_to "#{course.title}", course_path(course)
        -elsif course.title.downcase.include? "android"
          %tr
            %td= link_to image_tag("android.png"), "#"
            %td= link_to "#{course.title}", course_path(course)
        -elsif course.title.downcase.include? "html5"
          %tr
            %td= link_to image_tag("html5.jpg"), "#"
            %td= link_to "#{course.title}", course_path(course)
        -elsif  course.title.downcase.include? "rails"
          %tr
            %td= link_to image_tag("rails.png"), "#"
            %td= link_to "#{course.title}", course_path(course)
        -elsif  course.title.downcase.include? "java"
          %tr
            %td= link_to image_tag("java1.png"), "#"
            %td= link_to "#{course.title}", course_path(course)
        -else 
          %tr
            %td= link_to image_tag("rails.png"), "#"
            %td= link_to "#{course.title}", course_path(course)
          -#%td= "#{course.content}"
          
-# add to end of index.html.haml
-if not current_user.nil? and current_user.instruc
  = link_to 'Add new Course', new_course_path

app/views/courses/load.html.haml
= video_tag (["movie.mp4", "movie.ogg", "movie.webm"] :size => "320x240", :controls => true, :autobuffer => true)

app/views/courses/myvideo.html.haml
%video{:controls => "controls", :height => "240", :width => "320"}
  %source{:src => "/public/videos/try.flv"}/
  Your browser does not support the video tag.

app/views/courses/new.html.haml
%h1 New course
.row
  .span6.offset3
    = simple_form_for :course, :url => {:action => :create } do |f|
      %p= f.label :Course_Title
      %p= f.text_field :title
      %p= f.label :Points
      %p= f.text_field :points
      %p= f.label :Description
      %p= f.text_area :content, :rows => 5, :class => "span3", :placeholder => "Enter text"
      %p= f.submit "Create course", class: "btn btn-large btn-primary"

app/views/courses/show.html.haml
%center
  %div#description!= @course.render_content 
  -if current_user and not current_user.admin and not current_user.instruc
    = form_tag({:controller => :submissions, :action => :upload}, {:multipart => true, :method => :post, :html => { :class => "form-horizontal"}}) do
      = file_field_tag 'attachment'
      -#.form-actions
      %p= submit_tag "Upload" , class: "btn btn-medium btn-primary" 
    = button_to 'submit assignment', submit_path(@course), class: "btn btn-medium btn-primary"
    = link_to 'Back to course list',courses_path
 
-if current_user and current_user.instruc
  %p= link_to "Edit #{@course.title}", edit_course_path(@course)
  %p= link_to 'Back to course list',courses_path  
  %p= link_to 'Delete',course_path(@course), :method => :delete, data: {confirm: "Are You Sure? "}

app/views/courses/tag.html.haml
<iframe title="Video intro" #{video_tag "movie.AVI", :size => "350x350", :autoplay=> "true"} frameborder="0" >

app/views/courses/upload.html.haml
%h1 File Upload
= form_tag({:action => 'uploadFile'}, :multipart => true) do
  %p
    %label{:for => "upload_file"} Select File
    = file_field 'upload', 'datafile'
  = submit_tag "Upload"