config/routes.rb
HospitalLink::Application.routes.draw do
  

  root  to: 'static_pages#home', via: 'get'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :submissions
  resources :courses
  resources :attachments
  resources :credits
  post '/submit/:course', to: 'submissions#submit', as: :submit
  post '/upload', to: 'submissions#upload' , as: :upload
  get  '/download', to: 'submissions#download' , as: :download
  get '/instructors/request/accept/:id', to: 'users#accept' , as: :accept_request
  get '/instructors/requests', to: 'users#requests', as: :request
  get 'submissions/grades/pending' ,to: 'submissions#assignments_to_grade', as: :assign_to_grade
  get '/student/grades/:id', to: 'submissions#my_grades', as: :my_grades
  get '/students/submissions/:id', to: 'submissions#student', as: :student_submissions
  get '/students/points/:id', to: 'submissions#student_rewards', as: :student_rewards
  get 'tags/:tag', to: 'courses#index', as: :tag
  get 'students/rewards/:id' , to: 'submissions#tutorials_completed', as: :rewards
  match '/instructors', to: 'users#instructors', via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signup/students', to: 'users#new' , via: 'get'
  match '/help', to:  'static_pages#help' , via: 'get'
  match '/about', to:   'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact' , via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/signup/instructors', to: 'users#new_instructors', via: 'get'
  match '/create/instructors', to: 'users#create_instructors', via: 'post'
  match '/students', to: 'users#students', via: 'get'

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    =link_to "ImagineWare" , root_path
    by CS169 Group19
  %nav
    %ul
      %li= link_to "About",   about_path
      %li= link_to "Contact", contact_path
      %li
        =link_to " News" , root_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to "ImagineWare", root_path, id: "logo"
      %nav
        %ul.nav.pull-right
          %li= link_to "Home", root_path

          - if signed_in? 
            -if current_user.instruc? 
              %li#fat-menu.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  Tools
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to "Assignments to grade", assign_to_grade_path

              %li= link_to "Courses", courses_path
              %li= link_to "All Students", students_path
            -elsif current_user.admin?
              %li#fat-menu.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  Tools
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to "Instructor requests", request_path

              %li= link_to "Courses", courses_path
              %li= link_to "All Students", students_path
              %li= link_to "All instructors", instructors_path
            -else
              %li#fat-menu.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown",:href => "#"}
                  Tools
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to "My rewards", rewards_path(current_user)
              %li= link_to "Courses", courses_path
              %li= link_to "Grades", my_grades_path(current_user)
            %li#fat-menu.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Account
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Profile", current_user
                %li= link_to "Settings", edit_user_path(current_user)
                %li.divider
                %li
                  = link_to "Sign out", signout_path, method: "delete"

          - else
            %li= link_to "Help", help_path
            %li= link_to "Sign in", signin_path
            %li#fat-menu.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Sign Up
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Students",signup_students_path
                %li= link_to "Instructors",signup_instructors_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/layouts/app.html.haml
!!!
%html
  %head
    %title= content_for?(:title) ? yield(:title) : "Untitled"
    = stylesheet_link_tag "application"
    = javascript_include_tag :defaults
    = csrf_meta_tag
    = yield(:head)
    = javascript_include_tag 'jquery-1.9.1.js', 'jquery-ui-1.10.3.custom.min.js', 'autocomplete-rails.js',  'rails.js'
    = stylesheet_link_tag 'jquery-ui-1.10.3.custom.css'
  %body
    #container
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"
      = content_tag :h1, yield(:title) if show_title?
      = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag "application", media: "all", |
      "data-turbolinks-track" => true              |
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = yield(:head)
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container
      - flash.each do |key, value|
        %div{:class => "alert alert-#{key}"}= value
      = yield
      = render 'layouts/footer'

app/views/layouts/flash.html.haml
- flash.each do |key, value|
  %div{:class => "alert alert-#{key}"}= value